/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package echoClient;

import org.junit.Test;
import static org.junit.Assert.*;

public class echoClientTest {
    @Test public void testAppHasAGreeting() {
        echoClient classUnderTest = new echoClient();
        assertNotNull("app should have a greeting", classUnderTest);
    }
}
